<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

In [2]:
import os

In [4]:
datos = os.listdir()
datos

['laboratorio-modulo2-leccion01-numpy.ipynb',
 'laboratorio-modulo2-leccion05-limpieza.ipynb',
 'laboratorio-modulo2-leccion04-visualizacion.ipynb',
 'laboratorio-modulo2-leccion03-groupby.ipynb',
 'laboratorio-modulo2-leccion02-eda-union.ipynb',
 'laboratorio-modulo2-leccion03-filtrado.ipynb']

In [ ]:
diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}

diccioanrio_df = {}
for i in datos:
    df = pd.read_csv(i)
    diccioanrio_df[i.spl]


NameError: name 'datos' is not defined

for i in datos
# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [6]:
import numpy as np

In [7]:
array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [8]:
array_2d = array_1d.reshape(2, 5)
print(array_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [9]:
array = np.array([0, 2, 0, 3, 0, 4, 0])
indices = np.nonzero(array)
print(indices)

(array([1, 3, 5]),)


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [10]:
array_random = np.random.rand(3, 3)
print(array_random)

[[0.53361808 0.50470123 0.83639979]
 [0.00375871 0.59678481 0.6218013 ]
 [0.20008296 0.43256747 0.79365143]]


#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [11]:
array_random_10 = np.random.rand(10)

In [12]:
max_value = array_random_10.max()
min_value = array_random_10.min()
print(f"Máximo: {max_value}, Mínimo: {min_value}")

Máximo: 0.7496947124378318, Mínimo: 0.16729544615664038


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [13]:
array_invertido = array_1d[::-1]
print(array_invertido)

[9 8 7 6 5 4 3 2 1 0]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [14]:
array_3d = np.arange(1, 25).reshape(2, 3, 4)
print("Array 3D:")
print(array_3d)

Array 3D:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [15]:
primer_15 = array_3d[1, 0, 2]
print("\nEl primer 15 del array es:", primer_15)


El primer 15 del array es: 15


In [16]:
primer_bloque = array_3d[0]
print("\nPrimer bloque:")
print(primer_bloque)


Primer bloque:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
ultima_fila = array_3d[1, 2]
print("\nÚltima fila del último bloque:")
print(ultima_fila)


Última fila del último bloque:
[21 22 23 24]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [4]:
array_3d = np.arange(1, 31).reshape(3, 2, 5)

NameError: name 'np' is not defined

In [5]:
subarray_1 = array_3d[0, :, :2]
print(subarray_1)

NameError: name 'array_3d' is not defined

In [3]:
subarray_2 = array_3d[1:, :, :]
print(subarray_2)

NameError: name 'array_3d' is not defined

#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [ ]:
array_3d = np.arange(1, 25).reshape(4, 3, 2)

In [ ]:
array_3d[1, 1, :] = 0

In [ ]:
array_3d[-1, :, :] = -1
print(array_3d)


#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [ ]:
array_3d = np.random.randint(-10, 14, (2, 4, 3))

In [ ]:
mayores_a_5 = array_3d[array_3d > 5]


array_3d[array_3d < 0] = 0

In [ ]:
print(array_3d)
print(mayores_a_5)

#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [ ]:
array_3d = np.arange(1, 28).reshape(3, 3, 3)

In [ ]:
subarray = array_3d[1, :, :2]

mayores_20 = array_3d[2, array_3d[2] > 20]

In [ ]:
print(subarray)
print(mayores_20)

#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [ ]:
array = np.random.randint(1, 100, 10)
array[array == array.max()] = 0
array[array == array.min()] = 0
print(array)

#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [ ]:
array_ordenado = np.random.randint(1, 100, 15)
array_ordenado.sort()
print(array_ordenado)

#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [ ]:
matriz = np.random.randint(1, 10, (4, 4))
print("Matriz 4x4:")
print(matriz)

In [ ]:
suma_filas = np.sum(matriz, axis=1)
print("\nSuma de elementos por fila:")
print(suma_filas)

In [ ]:
suma_columnas = np.sum(matriz, axis=0)
print("\nSuma de elementos por columna:")
print(suma_columnas)

#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [ ]:
matriz_5x5 = np.zeros((5, 5), dtype=int)

In [ ]:
matriz_5x5[0, :] = 1  
matriz_5x5[-1, :] = 1  
matriz_5x5[:, 0] = 1 
matriz_5x5[:, -1] = 1  

print("Matriz 5x5 con bordes 1 y interior 0:")
print(matriz_5x5)


#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [ ]:
array = np.random.rand(10)
media = array.mean()
desviacion = array.std()
print(f"Media: {media}, Desviación estándar: {desviacion}")

#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [ ]:
array_3d = np.arange(1, 25).reshape(2, 3, 4)

In [ ]:
transpuesto = array_3d.transpose(2, 1, 0)
print(transpuesto)

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [ ]:
array_3d = np.arange(1, 25).reshape(3, 4, 2)
print("Array original (3, 4, 2):")
print(array_3d)

In [ ]:
array_transpuesto = array_3d.transpose(1, 0, 2)
print("\nArray transpuesto (4, 3, 2):")
print(array_transpuesto)


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [ ]:
array_3d = np.arange(1, 25).reshape(3, 2, 4)
print("Array original (3, 2, 4):")
print(array_3d)

In [ ]:
array_rotado = np.transpose(array_3d, (2, 0, 1))
print("\nArray rotado (4, 3, 2):")
print(array_rotado)

#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [ ]:
array_original = np.random.randint(-10, 11, (3, 4, 5))  
print(array_original)

In [ ]:
array_resultado = np.empty_like(array_original, dtype=object)

In [ ]:
mediana = np.median(array_original)
maximo = np.max(array_original)
minimo = np.min(array_original)

print(f"Mediana: {mediana}, Máximo: {maximo}, Mínimo: {minimo}")

In [ ]:
for i in range(array_original.shape[0]):  
    for j in range(array_original.shape[1]):  
        for k in range(array_original.shape[2]):  
            valor = array_original[i, j, k]
            if valor == mediana:
                array_resultado[i, j, k] = "M"
            elif valor > mediana:

#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [ ]:
array = np.random.randint(1, 10, (4, 4))
coincidencia = False

In [ ]:
for i in range(array.shape[0]):
    for j in range(array.shape[1]):
        if all(array[i] == array[:, j]):
            coincidencia = True
            print(f"La fila {i} es igual a la columna {j}.")

In [ ]:
if not coincidencia:
    print("No hay filas iguales a columnas.")